
 R14 = () => {
    $("#a1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni3').hide();
    $('#GlavniMeni2').show();
  }
  R15 = () => {
    $("#b1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni3').show();
    $('#GlavniMeni2').hide();
  }

  R16 = () => {
    $("#c1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni3').hide();
    $('#GlavniMeni4').show();
  }

  R16S = () => {
    $("#d1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni3').hide();
    $('#GlavniMeni4').hide();
    $('#GlavniMeni5').show();
  }

  R17 = () => {
    $("#e1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni3').hide();
    $('#GlavniMeni4').hide();
    $('#GlavniMeni5').hide();
    $('#GlavniMeni6').show();
  }

  R18 = () => {
    $("#f1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni2').hide();
    $('#GlavniMeni3').hide();
    $('#GlavniMeni4').hide();
    $('#GlavniMeni5').hide();
    $('#GlavniMeni6').hide();
    $('#GlavniMeni7').show();
  }

  R19 = () => {
    $("#g1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni3').hide();
    $('#GlavniMeni4').hide();
    $('#GlavniMeni5').hide();
    $('#GlavniMeni6').hide();
    $('#GlavniMeni7').hide();
    $('#GlavniMeni8').show();
  }

  R20 = () => {
    $("#j1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni3').hide();
    $('#GlavniMeni4').hide();
    $('#GlavniMeni5').hide();
    $('#GlavniMeni6').hide();
    $('#GlavniMeni7').hide();
    $('#GlavniMeni8').hide();
    $('#GlavniMeni9').show();
  }

  R21 = () => {
    $("#i1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni3').hide();
    $('#GlavniMeni4').hide();
    $('#GlavniMeni5').hide();
    $('#GlavniMeni6').hide();
    $('#GlavniMeni7').hide();
    $('#GlavniMeni8').hide();
    $('#GlavniMeni9').hide();
    $('#GlavniMeni10').show();
  }

  R22 = () => {
    $("#k1").show();
    $('#GlavniMeniS').hide();
    $('#GlavniMeni3').hide();
    $('#GlavniMeni4').hide();
    $('#GlavniMeni5').hide();
    $('#GlavniMeni6').hide();
    $('#GlavniMeni7').hide();
    $('#GlavniMeni8').hide();
    $('#GlavniMeni9').hide();
    $('#GlavniMeni10').hide();
    $('#GlavniMeni11').show();
  }


  //R14
  $("#Odgo1").click(function(){
    $("#a1").hide();
    $("#a1Yes").show();
  });
  $("#Odgo2").click(function(){
    $("#a1").hide();
    $("#a1No").show();
  });

  //R15
  $("#Odgovor1S").click(function(){
    $("#b1").hide();
    $("#b1Yes").show();
  });
  $("#Odgovor2S").click(function(){
    $("#b1").hide();
    $("#b1No").show();

  });$("#Odgovor5S").click(function(){
    $("#b1Yes").hide();
    $("#b2Yes").show();
  });
  $("#Odgovor6S").click(function(){
    $("#b1Yes").hide();
    $("#b2No").show();
  });
  
  //R16
  $("#Answer1S").click(function(){
    $("#c1").hide();
    $("#c1Yes").show();
  });
  $("#Answer2S").click(function(){
    $("#c1").hide();
    $("#c1No").show();
  });

  //R16S
  $("#Ansr1S").click(function(){
    $("#d1").hide();
    $("#d1Yes").show();
  });
  $("#Ansr2S").click(function(){
    $("#d1").hide();
    $("#d1No").show();

  });$("#Ansr5S").click(function(){
    $("#d1Yes").hide();
    $("#d2Yes").show();
  });
  $("#Ansr6S").click(function(){
    $("#d1Yes").hide();
    $("#d2No").show();
  });

  //R17
  $("#Odgo1SS").click(function(){
    $("#e1").hide();
    $("#e1Yes").show();
  });
  $("#Odgo2SS").click(function(){
    $("#e1").hide();
    $("#e1No").show();
  });

  //R18
  $("#Odgovor1SS").click(function(){
    $("#f1").hide();
    $("#f1Yes").show();
  });
  $("#Odgovor2SS").click(function(){
    $("#f1").hide();
    $("#f1No").show();

  });$("#Odgovor5SS").click(function(){
    $("#f1Yes").hide();
    $("#f2Yes").show();
  });
  $("#Odgovor6SS").click(function(){
    $("#f1Yes").hide();
    $("#f2No").show();
  });

  //R19
  $("#Odg1SS").click(function(){
    $("#g1").hide();
    $("#g1Yes").show();
  });
  $("#Odg2SS").click(function(){
    $("#g1").hide();
    $("#g1No").show();
  });
  $("#Odg3SS").click(function(){
    $("#g1No").hide();
    $("#g2Yes").show();
  });
  $("#Odg4SS").click(function(){
    $("#g1No").hide();
    $("#g2No").show();
  });
  $("#Odg7SS").click(function(){
    $("#g2No").hide();
    $("#g3Yes").show();
  });
  $("#Odg8SS").click(function(){
    $("#g2No").hide();
    $("#g3No").show();
  });
  
  //R20
  $("#Odg1SSS").click(function(){
    $("#j1").hide();
    $("#j1Yes").show();
  });
  $("#Odg2SSS").click(function(){
    $("#j1").hide();
    $("#j1No").show();
  });
  $("#Odg3SSS1").click(function(){
    $("#j1Yes").hide();
    $("#j2Yes").show();    
  });
  $("#Odg4SSS1").click(function(){
    $("#j1Yes").hide();
    $("#j2No").show();
  });
  $("#Odg7SSS").click(function(){
    $("#j2No").hide();
    $("#j3Yes").show();
  });
  $("#Odg8SSS").click(function(){
    $("#j2No").hide();
    $("#j3No").show();
  });

  //R21
  $("#Odgovor1SSS").click(function(){
    $("#i1").hide();
    $("#i1Yes").show();
  });
  $("#Odgovor2SSS").click(function(){
    $("#i1").hide();
    $("#i1No").show();
  });
  $("#Odgovor5SSS").click(function(){
    $("#i1Yes").hide();
    $("#i2Yes").show();    
  });
  $("#Odgovor6SSS").click(function(){
    $("#i1Yes").hide();
    $("#i2No").show();
  });
  $("#Odgovor7SSS").click(function(){
    $("#i2No").hide();
    $("#i3Yes").show();
  });
  $("#Odgovor8SSS").click(function(){
    $("#i2No").hide();
    $("#i3No").show();
  });
  $("#Odgovor9SSS").click(function(){
    $("#i3No").hide();
    $("#i4Yes").show();
  });
  $("#Odgovor10SSS").click(function(){
    $("#i3No").hide();
    $("#i4No").show();
  });
  $("#Odgovor11SSS").click(function(){
    $("#i4No").hide();
    $("#i5Yes").show();    
  });
  $("#Odgovor12SSS").click(function(){
    $("#i4No").hide();
    $("#i5No").show();
  });

  //R22
  $("#Odgo1SSS").click(function(){
    $("#k1").hide();
    $("#k1Yes").show();
  });
  $("#Odgo2SSS").click(function(){
    $("#k1").hide();
    $("#k1No").show();
  })


  function Reset1() {
    $("#a1").show();
    $("#a1No").hide();
    $("#a1Yes").hide();
    $("#a2No").hide();
    $("#a2Yes").hide();
    $("#a3No").hide();
    $("#a3Yes").hide();
    $("#a4No").hide();
    $("#a4Yes").hide();
    $("#a5No").hide();
    $("#a5Yes").hide();
    $("#a6No").hide();
    $("#a6Yes").hide();
    $("#a7No").hide();
    $("#a7Yes").hide();
    $("#a8No").hide();
    $("#a8Yes").hide();
    $("#a9No").hide();
    $("#a9Yes").hide();
    $("#a10No").hide();
    $("#a10Yes").hide();
    $("#a11No").hide();
    $("#a11Yes").hide();
    $("#b1").show();
    $("#b1No").hide();
    $("#b1Yes").hide();
    $("#b2No").hide();
    $("#b2Yes").hide();
    $("#b3No").hide();
    $("#b3Yes").hide();
    $("#b4No").hide();
    $("#b4Yes").hide();
    $("#b5No").hide();
    $("#b5Yes").hide();
    $("#b6No").hide();
    $("#b6Yes").hide();
    $("#b7No").hide();
    $("#b7Yes").hide();
    $("#b8No").hide();
    $("#b8Yes").hide();
    $("#b9No").hide();
    $("#b9Yes").hide();
    $("#b10No").hide();
    $("#b10Yes").hide();
    $("#b11No").hide();
    $("#b11Yes").hide();
    $("#b12Yes").hide();
    $("#b13Yes").hide();
    $("#b13No").hide();
    $("#b14Yes").hide();
    $("#b15Yes").hide();
    $("#b15No").hide();
    $("#b16Yes").hide();
    $("#b16No").hide();
    $("#b17Yes").hide();
    $("#b17No").hide();
    $("#b18Yes").hide();
    $("#b18No").hide();
    $("#b19Yes").hide();
    $("#b19No").hide();
    $("#b20Yes").hide();
    $("#b20No").hide();
    $("#b21Yes").hide();
    $("#b21No").hide();
    $("#b22Yes").hide();
    $("#b22No").hide();
    $("#b23Yes").hide();
    $("#b23No").hide();
    $("#b24Yes").hide();
    $("#b24No").hide();
    $("#b25Yes").hide();
    $("#b25No").hide();
    $("#b26Yes").hide();
    $("#b26No").hide();
    $("#b27Yes").hide();
    $("#b27No").hide();
    $("#b28Yes").hide();
    $("#b28No").hide();
    $("#b29Yes").hide();
    $("#b29No").hide();
    $("#b30Yes").hide();
    $("#b30No").hide();
    $("#b31Yes").hide();
    $("#b31No").hide();
    $("#b32Yes").hide();
    $("#b32No").hide();
    $("#b33Yes").hide();
    $("#b33No").hide();
    $("#b34Yes").hide();
    $("#b34No").hide();
    $("#b35Yes").hide();
    $("#b35No").hide();
    $("#b36Yes").hide();
    $("#b36No").hide();
    $("#b37Yes").hide();
    $("#b37No").hide();
    $("#b38Yes").hide();
    $("#b38No").hide();
    $("#b39Yes").hide();
    $("#b39No").hide();
    $("#b40Yes").hide();
    $("#b40No").hide();
    $("#b41Yes").hide();
    $("#b41No").hide();
    $("#b42Yes").hide();
    $("#b42No").hide();
    $("#b43Yes").hide();
    $("#b43No").hide();
    $("#c1").hide();
    $("#c1").show();
    $("#c1No").hide();
    $("#c1Yes").hide();
    $("#c2No").hide();
    $("#c2Yes").hide();
    $("#c3No").hide();
    $("#c3Yes").hide();
    $("#c4No").hide();
    $("#c4Yes").hide();
    $("#c5No").hide();
    $("#c5Yes").hide();
    $("#c6No").hide();
    $("#c6Yes").hide();
    $("#c7No").hide();
    $("#c7Yes").hide();
    $("#c8No").hide();
    $("#c8Yes").hide();
    $("#c9No").hide();
    $("#c9Yes").hide();
    $("#c10No").hide();
    $("#c10Yes").hide();
    $("#c11No").hide();
    $("#c11Yes").hide();
    $("#c12No").hide();
    $("#c12Yes").hide();
    $("#c13No").hide();
    $("#c13Yes").hide();
    $("#c14No").hide();
    $("#c14Yes").hide();
    $("#c15No").hide();
    $("#c15Yes").hide();
    $("#c16No").hide();
    $("#c16Yes").hide();
    $("#c17No").hide();
    $("#c17Yes").hide();
    $("#c18No").hide();
    $("#c18Yes").hide();
    $("#c19No").hide();
    $("#c19Yes").hide();
    $("#c20No").hide();
    $("#c20Yes").hide();
    $("#c21No").hide();
    $("#c21Yes").hide();
    $("#c22No").hide();
    $("#c22Yes").hide();
    $("#c23No").hide();
    $("#c23Yes").hide();
    $("#d1").show();
    $("#d1No").hide();
    $("#d1Yes").hide();
    $("#d2No").hide();
    $("#d2Yes").hide();
    $("#d3No").hide();
    $("#d3Yes").hide();
    $("#d4No").hide();
    $("#d4Yes").hide();
    $("#d5No").hide();
    $("#d5Yes").hide();
    $("#d6No").hide();
    $("#d6Yes").hide();
    $("#d7No").hide();
    $("#d7Yes").hide();
    $("#d8No").hide();
    $("#d8Yes").hide();
    $("#d9No").hide();
    $("#d9Yes").hide();
    $("#d10No").hide();
    $("#d10Yes").hide();
    $("#d11No").hide();
    $("#d11Yes").hide();
    $("#d12No").hide();
    $("#d12Yes").hide();
    $("#d13No").hide();
    $("#d13Yes").hide();
    $("#d14No").hide();
    $("#d14Yes").hide();
    $("#d15No").hide();
    $("#d15Yes").hide();
    $("#d16No").hide();
    $("#d16Yes").hide();
    $("#d17No").hide();
    $("#d17Yes").hide();
    $("#d18No").hide();
    $("#d18Yes").hide();
    $("#d19No").hide();
    $("#d19Yes").hide();
    $("#d20No").hide();
    $("#d20Yes").hide();
    $("#d21No").hide();
    $("#d21Yes").hide();
    $("#d22No").hide();
    $("#d22Yes").hide();
    $("#d23No").hide();
    $("#d23Yes").hide();
    $("#e1").show();
    $("#e1No").hide();
    $("#e1Yes").hide();
    $("#f1").show();
    $("#f1No").hide();
    $("#f1Yes").hide();
    $("#f2No").hide();
    $("#f2Yes").hide();
    $("#g1").show();
    $("#g1No").hide();
    $("#g1Yes").hide();
    $("#g2No").hide();
    $("#g2Yes").hide();
    $("#g3No").hide();
    $("#g3Yes").hide();
    $("#j1").show();
    $("#j1No").hide();
    $("#j1Yes").hide();
    $("#j2No").hide();
    $("#j2Yes").hide();
    $("#j3No").hide();
    $("#j3Yes").hide();
    $("#i1").show();
    $("#i1No").hide();
    $("#i1Yes").hide();
    $("#i2No").hide();
    $("#i2Yes").hide();
    $("#i3No").hide();
    $("#i3Yes").hide();
    $("#i4No").hide();
    $("#i4Yes").hide();
    $("#i5No").hide();
    $("#i5Yes").hide();
    $("#k1").show();
    $("#k1No").hide();
    $("#k1Yes").hide();
  }
  